In [2]:
import numpy as np

In [4]:
ar = np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

In [6]:
2*ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
len(c)

2

In [14]:
len(c[0])

3

In [17]:
d = np.arange(10,50,10)
e = np.arange(50,90,10)
f = np.array([d,e])
f

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [18]:
print(f.ndim)

2


In [20]:
m = np.array([[0,1,2,3,4], [5,6,7,8,9], [10,1,12,13,14]])

In [22]:
m[1,2]

7

In [23]:
m[2,4]

14

In [26]:
m[1,1:3]

array([6, 7])

In [28]:
m[1:,2]

array([ 7, 12])

In [30]:
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

In [31]:
a = np.array([0,1,2,3])
idx = np.array([True, False, True, True])
a[idx]

array([0, 2, 3])

In [32]:
x = np.arange(1,21,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
##3의 배수
three = []
for i in x:
    if i%3 == 0 :
        three.append(i)
three

[3, 6, 9, 12, 15, 18]

In [35]:
x[x%3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [36]:
x[x%4 == 0]

array([ 4,  8, 12, 16, 20])

In [39]:
np.log(0)

<ipython-input-39-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [45]:
np.log(1)

0.0

In [48]:
np.exp(10)

22026.465794806718

In [49]:
e = np.ones([2,3,4], dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [52]:
b = np.zeros([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
f = np.ones_like(b, dtype = "f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [55]:
g = np.empty((4,3)) ## 리소스를 절약하기 위해 사용
g

array([[1.11733119e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.73734844e-047],
       [3.80208114e+175, 9.76480941e+165, 1.48616051e-076],
       [1.21647644e-046, 3.70018994e-033, 3.50909806e-033]])

In [56]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [57]:
np.logspace(0.1,1,10) ## 10의 0.1승부터 10의 1승까지

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [76]:
A = np.arange(1,13)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
A = A.reshape(3,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
A.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [67]:
A.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
B = A.flatten()
print(B)
print(type(B))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>


In [74]:
C = A.ravel()
print(C)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [77]:
A[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [88]:
a = np.ones((3,4))
b = np.zeros((3,4))
np.dstack([a,b])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [90]:
np.tile(0,12)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
a = np.arange(3)
b = np.arange(5)
A,B = np.meshgrid(a,b)

In [94]:
a

array([0, 1, 2])

In [95]:
b

array([0, 1, 2, 3, 4])

In [92]:
A

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [93]:
B

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [112]:
%%time
sum = 0
for i in range(100000000) :
    sum += i
    
print(sum)

4999999950000000
Wall time: 9.46 s


In [108]:
X = np.array([[1,2,3,],
            [4,5,6]])
Y = np.array([[10,100,1000],
            [10000,100000,1000000]])
X+Y

array([[     11,     102,    1003],
       [  10004,  100005, 1000006]])

In [109]:
np.dot(X,Y.T)

array([[   3210, 3210000],
       [   6540, 6540000]])

In [111]:
x2 = np.array([1,1,2,3,5,7]).reshape(2,3)
np.savetxt("경로", x2)

In [ ]:
a = np.loadtxt("경로", delimiter=",")
a